[2022-05-30 20:30:31,916] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest manual__2022-05-30T20:30:27.970218+00:00 [queued]>
[2022-05-30 20:30:31,926] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest manual__2022-05-30T20:30:27.970218+00:00 [queued]>
[2022-05-30 20:30:31,928] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 20:30:31,929] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 20:30:31,930] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 20:30:31,943] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2022-05-30 20:30:27.970218+00:00
[2022-05-30 20:30:31,950] {standard_task_runner.py:52} INFO - Started process 1839 to run task
[2022-05-30 20:30:31,956] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'manual__2022-05-30T20:30:27.970218+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpraf7n7_y', '--error-file', '/tmp/tmpjngyenlk']
[2022-05-30 20:30:31,959] {standard_task_runner.py:80} INFO - Job 161: Subtask ingest
[2022-05-30 20:30:32,083] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest manual__2022-05-30T20:30:27.970218+00:00 [running]> on host e083cbf9476b
[2022-05-30 20:30:32,146] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 20:30:32,200] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2022-05-30T20:30:27.970218+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-30T20:30:27.970218+00:00
[2022-05-30 20:30:32,207] {logging_mixin.py:115} INFO - yellow_taxi_2022_05 /opt/***/output_2022-05.parquet 2022-05-30T20:30:27.970218+00:00
[2022-05-30 20:30:32,208] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 12, in ingest_callable
    engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{db}')
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 518, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 711, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 772, in _parse_rfc1738_args
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: 'None'
[2022-05-30 20:30:32,224] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20220530T203027, start_date=20220530T203031, end_date=20220530T203032
[2022-05-30 20:30:32,236] {standard_task_runner.py:97} ERROR - Failed to execute job 161 for task ingest (invalid literal for int() with base 10: 'None'; 1839)
[2022-05-30 20:30:32,299] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-30 20:30:32,347] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
